### ISSUE TITLE
Importación del Certificado

### ISSUE THREAD

**Issue by factronico** [LibreDTE/libredte-sowerphp#1]
Al importar el certificado arroja este error:
Lo intente con .pfx y .p12 pero con ninguno logró realizar la importación.

Ocurrió un error al guardar la firma.
23502 7 ERROR: null value in column "run" violates not-null constraint INSERT INTO firma_electronica ( nombre, email, desde, hasta, emisor, usuario, archivo, contrasenia ) VALUES ( :nombre, :email, :desde, :hasta, :emisor, :usuario, :archivo, :contrasenia )

**Comment by estebandelaf** [comment]
Hola, es muy probable que el error este asociado a otro reporte que hicieron en el grupo de google[1] Básicamente es que la clase FirmaElectronica obtiene el serialNumber desde el certificado, y por el otro reporte[1] algunos certificados no tendrían ese serialNumber. Estoy esperando que ese usuario me conteste algo que le pedí para ver si el RUN en su caso es almacenado en otro campo del certificado. Ahora si puedes hacer la prueba tu e indicarmelo lo agradecería (en el enlace [1] hay mas detalles).

Esta issue quedará abierta hasta solucionar el problema de carga del certificado  la base de datos.

[1] https://groups.google.com/d/msg/libredte/f4rzrcLl6Z0/Q1t8qWVyDAAJ

**Comment by estebandelaf** [comment]
Se corrigió para certificados E-Sign[1], por favor confirmar si esto resuelve el problema en tu caso. Otros certificados podrían tener el RUN guardad en otro campo.

Saludos!

[1] https://groups.google.com/d/msg/libredte/f4rzrcLl6Z0/vri3pa4DAwAJ

**Comment by estebandelaf** [comment]
Se agreggó soporte para E-CERTCHILE[1] de acuerdo a listado de firmas oficiales[2] sólo falta agregar el soporte para certificados de CERTINET.

[1] https://github.com/LibreDTE/libredte-lib/commit/84293b898927cb8e3a978b8fb2fcd536cdd48359
[2] https://palena.sii.cl/dte/mn_Prov_CD.html

**Comment by estebandelaf** [comment]
Son 5 las empresas autorizadas a emitir firmas[1], no 4 (la página del SII[2] está desactualizada ¬¬). 

Se agregó soporte para PKI Chile: Paperless[3]. Sigue faltando el soporte para CERTINET.

[1] https://github.com/LibreDTE/libredte-lib/commit/0faf45e8107735e3460d5a5f299f92af60b4d81b
[2] https://palena.sii.cl/dte/mn_Prov_CD.html
[3] http://www.entidadacreditadora.gob.cl/?page_id=136

**Comment by estebandelaf** [comment]
Se me ocurrió revisar si Acepta e E-Sign guardaban el RUN en la extensión, al igual que PAPERLESS y E-CERTCHILE. Y efectivamente ahí lo guardan, mi confusión original era porque Acepta e E-sign además lo guardaban en otro lado. Asumiré que si los 4 proveedores lo guardan en la extensión, es la forma estándar de guardarlo ya que no me cuadra que cada proveedor lo guarde en un campo diferente. Por lo anterior, supongo el 5to proveedor estaría soportado y cierro la issue.
