### ISSUE TITLE
Error al registrar nuevo contribuyente

### ISSUE THREAD

**Issue by gamerjota** [LibreDTE/libredte-sowerphp#7]
¡Hola!
Hace poco descubrí que existe LibreDTE y decidí montar rápidamente un ambiente para probarlo.
Hasta ahora me he topado solo con un problema, al intentar enviar el formulario de registro de un nuevo contribuyente obtengo el siguiente error:

> Debe especificar: razon_social

Y la siguiente traza:

> #0 DIR_WEBSITE/Module/Dte/Model/Contribuyente.php(220): website\Dte\Model_Contribuyente->save()
#1 DIR_WEBSITE/Module/Dte/Controller/Contribuyentes.php(120): website\Dte\Model_Contribuyente->__construct('[ACÁ VA EL RUT DE LA EMPRESA]')
#2 [internal function]: website\Dte\Controller_Contribuyentes->registrar()
#3 DIR_FRAMEWORK/lib/sowerphp/core/Controller.php(191): ReflectionMethod->invoke(Object(website\Dte\Controller_Contribuyentes))
#4 DIR_FRAMEWORK/lib/sowerphp/core/Routing/Dispatcher.php(179): sowerphp\core\Controller->invokeAction()
#5 DIR_FRAMEWORK/lib/sowerphp/core/Routing/Dispatcher.php(72): sowerphp\core\Routing_Dispatcher::_invoke(Object(website\Dte\Controller_Contribuyentes), Object(sowerphp\core\Network_Request), Object(sowerphp\core\Network_Response))
#6 DIR_WEBSITE/webroot/index.php(52): sowerphp\core\Routing_Dispatcher::dispatch()
#7 {main}

Obviamente el formulario se envía solamente si se completan todos los campos, pero ni idea el por qué del error.

¿Será porque estoy usando PHP 5.6.17?
¡Saludos!

**Comment by estebandelaf** [comment]
Hola, ¿cuándo bajaste la aplicación? anoche se le hicieron múltiples cambios a la tabla contribuyente y ahora se hacen las validaciones de otra forma. Si por casualidad tuvieses mezclado el esquema antiguo con el código en PHP nuevo podrías tener problemas.

La verificación de los campos mínimos se hace acá: https://github.com/LibreDTE/libredte-sowerphp/blob/master/Model/Contribuyente.php#L319

Verifica que estés trabajando con el esquema actualizado (hay un comando para la terminal de SowerPHP que te permite migrar del antiguo esquema al nuevo) y que también tengas la última versión del código.

Atento a tus comentarios.

Saludos!

**Comment by gamerjota** [comment]
Baje todo una hora antes aproximadamente desde que hice la pregunta, ahora hace unos 30 minutos acabo de bajar todo denuevo probando en Wheezy (anteriormente estaba usando Amazon Linux) y me da exactamente el mismo error.
Con lo del comando para actualizar SowerPHP es con SowerPKG, ¿no?.
¡Gracias y saludos!

**Comment by estebandelaf** [comment]
Hola!

Al registrar un contribuyente por la página de creación de contribuyentes no hay problemas, de hecho registré uno nuevo el día de hoy. Donde si había un problema era al usar la API, al consumir la generación de XML se guardan los datos del emisor y receptor y se estaban validando datos que no se debían validar (sólo se validan al crear por la interfaz web el contribuyente).

De todas formas te recomiendo actualizar el módulo y la aplicación web. Durante el día de hoy también se hizo una mejora de seguridad al framework (extensión app específicamente), por lo que te recomiendo actualizar, y si, lo puedes hacer con SowerPKG que es más rápido y fácil.

Finalmente, te pido que me trates de adjuntar una imagen con el error que obtienes ya que me interesa ver exactamente que es lo que te indica la web (puedes subir la foto a algún otro lado y pegar el enlace aquí).

Saludos!

**Comment by gamerjota** [comment]
Okay, primero actualizo SowerPHP a través de SowerPKG:

> $ ./sowerpkg.sh install -e "empresa app general" -W
Instalando SowerPHP... OK!
 Instalando dependencias de composer... OK!
Instalando extensiones:
 - Instalando extensión empresa... OK!
    Instalando dependencias de composer... OK!
 - Instalando extensión app... OK!
    Instalando dependencias de composer... OK!
 - Instalando extensión general... OK!
    Instalando dependencias de composer... OK!
Log guardado en /tmp/sowerpkg_admin_20160129002204.log

Ahora revisamos el código de la aplicación web:

> $ sudo git pull
remote: Counting objects: 7, done.
remote: Compressing objects: 100% (2/2), done.
remote: Total 7 (delta 5), reused 7 (delta 5), pack-reused 0
Unpacking objects: 100% (7/7), done.
From https://github.com/LibreDTE/libredte-webapp
   346afd9..5a07ab2  master     -> origin/master
Fetching submodule website/Module/Dte
remote: Counting objects: 15, done.
remote: Compressing objects: 100% (4/4), done.
remote: Total 15 (delta 11), reused 15 (delta 11), pack-reused 0
Unpacking objects: 100% (15/15), done.
From https://github.com/LibreDTE/libredte-sowerphp
   fbf9f30..b9cfa57  master     -> origin/master
Updating 346afd9..5a07ab2
Fast-forward
 website/Module/Dte                      |    2 +-
 website/View/Utilidades/generar_xml.php |    7 -------
 2 files changed, 1 insertion(+), 8 deletions(-)

Y sigue con el mismo error de arriba.

Exception
> Debe especificar: razon_social

Traza

> #0 DIR_WEBSITE/Module/Dte/Model/Contribuyente.php(220): website\Dte\Model_Contribuyente->save()
#1 DIR_WEBSITE/Module/Dte/Controller/Contribuyentes.php(120): website\Dte\Model_Contribuyente->__construct('5206826')
#2 [internal function]: website\Dte\Controller_Contribuyentes->registrar()
#3 DIR_FRAMEWORK/lib/sowerphp/core/Controller.php(191): ReflectionMethod->invoke(Object(website\Dte\Controller_Contribuyentes))
#4 DIR_FRAMEWORK/lib/sowerphp/core/Routing/Dispatcher.php(179): sowerphp\core\Controller->invokeAction()
#5 DIR_FRAMEWORK/lib/sowerphp/core/Routing/Dispatcher.php(72): sowerphp\core\Routing_Dispatcher::_invoke(Object(website\Dte\Controller_Contribuyentes), Object(sowerphp\core\Network_Request), Object(sowerphp\core\Network_Response))
#6 DIR_WEBSITE/webroot/index.php(52): sowerphp\core\Routing_Dispatcher::dispatch()
#7 {main}

Screenshot: http://i.imgur.com/TkACoJW.png

¡Saludos nuevamente!

**Comment by estebandelaf** [comment]
¿Actualizaste el módulo?

```
$ cd website/Module/Dte
$ git pull
```

Saludos!

PD: para actualizar el framework lo haces con `sowerpkg.sh update` (el install te borra todo y hace todo de 0)

**Comment by gamerjota** [comment]
Por lo que entiendo en el pull de la carpeta libredte también se actualiza al ser un sub-módulo.

> Fetching submodule website/Module/Dte

Lo acabo de hacer nuevamente y estoy al día.

> Already up-to-date.

Ahora probando actualizar el framework con `sowerpkg.sh update` 

> $ sudo ./sowerpkg.sh update
Actualizando SowerPHP... OK!
 Actualizando dependencias de composer... OK!
 - Actualizando extensión empresa... OK!
    Actualizando dependencias de composer... OK!
 - Actualizando extensión app... OK!
    Actualizando dependencias de composer... OK!
 - Actualizando extensión general... OK!
    Actualizando dependencias de composer... OK!
Log guardado en /tmp/sowerpkg_root_20160129004605.log

Y seguimos con el mismo error.
Saludos.

**Comment by estebandelaf** [comment]
Al hacer el pull en la carpeta webapp lo que haces es actualizar el "estado" del módulo Dte, igualmente debes actualizar el módulo luego con git pull en el directorio website/Module/Dte

Saludos!

**Comment by gamerjota** [comment]
Ooh...
Hehe, gracias, ahora si todo en orden.
¡Saludos!
